# Tutorial 1 Fundamentals


Topics:
- (5 min) Python Lists Operations
- (10 min) NumPy Arrays & Sampling
- (10 min) How to Define a Python Class
- (30 min) Python Class of Single Layer Perceptron Classifier for XOR, AND Examples
- (5 min) Q&A

In [6]:
import numpy as np
import matplotlib.pyplot as plt

# Part 1: Python Lists Operations

In [7]:
# Creating a list
data = [0, 1, 2, 3, 4, 5]

In [8]:
data

[0, 1, 2, 3, 4, 5]

In [64]:
# Adding elements to the end of list
data.append(6)
print(data)

[0, 1, 2, 3, 4, 5, 6]


In [66]:
# Removing last element from a list
data.pop()

6

In [71]:
data

[0, 1, 2, 3, 4, 5]

In [69]:
# List concatenation
[-2, -1] + data

[-2, -1, 0, 1, 2, 3, 4, 5]

In [9]:
# Accessing a list like an array
data[2]

2

In [11]:
# Get the last element of the list
data[-2]

4

In [12]:
range(0, 50)  # iterator
list(range(0, 50))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [74]:
# Generating a list of numbers
data = list(range(0, 50))
print(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [13]:
# Fancier: list comprehension
data = [2*i+3 for i in range(0, 50) if i % 2 == 0]
# data = [func(i) for i in range(0, 50) if condition(i)]
print(data)

[3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75, 79, 83, 87, 91, 95, 99]


In [20]:
# List slicing syntax
data = list(range(0, 50))
# data[1:3]
# data[2:]
# data[:3]
# data[1:10:2]
# data[::-1]

In [85]:
data

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [81]:
data[0:4]

[0, 1, 2, 3]

In [86]:
data[10:1:2]

[]

In [87]:
data[10:1:-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2]

In [89]:
data[:-2]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47]

In [88]:
data[2:]

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [94]:
# "2D" lists
data = [[0, 1, 2, 4, 5, 6], [7, 8, 9, 10, 11, 12]]
print(data[1])
print(data[0][4])

[7, 8, 9, 10, 11, 12]
5


In [14]:
# Find all the even numbers elements in the 2D list
for row in data:
    for ele in row:
        if ele % 2 == 0:
            print(ele)

0
2
4
6
8
10
12


# Part 2: NumPy

In [27]:
data = [[0, 1, 2, 4, 5, 6], 
        [7, 8, 9, 10, 11, 12]]


In [25]:
data[0]

[0, 1, 2, 4, 5, 6]

In [26]:
data[1]

[7, 8, 9, 10, 11, 12, 13]

In [28]:
data_np = np.array(data)
print(data_np)

[[ 0  1  2  4  5  6]
 [ 7  8  9 10 11 12]]


In [29]:
data_np

array([[ 0,  1,  2,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
# Accessing via indices
data_np[0][4]

5

In [17]:
# A different way to access via indices
x = (0, 4) # tuple
data_np[x]

5

In [18]:
# Find all the elements in the third column
data_np[:, 2]

array([2, 9])

In [98]:
data_np[1, :]

array([ 7,  8,  9, 10, 11, 12])

In [30]:
# Find all the even numbers in the 2D list
data_np % 2 == 0

array([[ True, False,  True,  True, False,  True],
       [False,  True, False,  True, False,  True]])

In [20]:
data_np[data_np % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12])

In [99]:
# What are the indices of the even numbers
row_indices, col_indices = np.where(data_np % 2 == 0)
print(row_indices)
print(col_indices)

[0 0 0 0 1 1 1]
[0 2 3 5 1 3 5]


In [34]:
data_np.shape

(2, 6)

In [35]:
len(data_np)

2

In [36]:
data_np.size

12

## NumPy Array Operations

In [31]:
vec1 = np.array([0, 1, 2, 3, 4, 5])
vec2 = np.array([4, 2, 1, 3, 5, 6])

In [32]:
# Properties of arrays
print(len(vec1))
print(vec1.shape)
print(vec1.size)

6
(6,)
6


In [108]:
# Element-wise addition. + is different than lists!
vec1 + vec2

array([ 4,  3,  3,  6,  9, 11])

In [25]:
# Concatenate two arrays
np.concatenate([vec1, vec2])

array([0, 1, 2, 3, 4, 5, 4, 2, 1, 3, 5, 6])

In [26]:
np.hstack([vec1, vec2])

array([0, 1, 2, 3, 4, 5, 4, 2, 1, 3, 5, 6])

In [109]:
vec3 = np.vstack([vec1, vec2])
vec3

array([[0, 1, 2, 3, 4, 5],
       [4, 2, 1, 3, 5, 6]])

In [111]:
# Properties of 2D arrays
len(vec3)
print(vec3.shape)
vec3.ndim

(2, 6)


2

In [114]:
# Reshaping 
vec3.reshape(4, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [4, 2, 1],
       [3, 5, 6]])

In [30]:
# Some operations are not done in-place
vec3

array([[0, 1, 2, 3, 4, 5],
       [4, 2, 1, 3, 5, 6]])

In [115]:
# Numpy arrays datatype
vec3.dtype

dtype('int32')

In [116]:
vec3[0, 0] = 0.6
vec3

array([[0, 1, 2, 3, 4, 5],
       [4, 2, 1, 3, 5, 6]])

In [117]:
vec4 = vec3.astype(float)
vec4[0, 0] = 0.5
vec4

array([[0.5, 1. , 2. , 3. , 4. , 5. ],
       [4. , 2. , 1. , 3. , 5. , 6. ]])

## NumPy Array Math Operations

In [118]:
# Back to math, element-wise multiplication
vec1 * vec2

array([ 0,  2,  2,  9, 20, 30])

In [37]:
vec1 @ vec2  # @ operator means dot product (inner product)

63

In [119]:
# Broadcasting
vec1 * 5

array([ 0,  5, 10, 15, 20, 25])

In [40]:
# Matrix operations
X = (np.random.random((4, 4)) * 10).astype(int)
X

array([[8, 7, 6, 1],
       [4, 7, 7, 8],
       [9, 1, 5, 1],
       [5, 9, 3, 8]])

In [41]:
X.shape

(4, 4)

In [42]:
X @ X

array([[151, 120, 130,  78],
       [163, 156, 132, 131],
       [126,  84,  89,  30],
       [143, 173, 132, 144]])

In [122]:
# Transpose
X.T

array([[3, 0, 8, 5],
       [7, 0, 9, 9],
       [8, 4, 6, 7],
       [0, 1, 6, 2]])

In [123]:
# Inverse
X_inv = np.linalg.inv(X)
X_inv

array([[ 1.51485149, -0.77227723,  0.78217822, -1.96039604],
       [-0.81188119,  0.21782178, -0.42574257,  1.16831683],
       [ 0.26732673,  0.0990099 ,  0.07920792, -0.28712871],
       [-1.06930693,  0.6039604 , -0.31683168,  1.14851485]])

In [124]:
# Matrix multiplication
# AB = A@B
X @ X_inv

array([[ 1.00000000e+00, -6.66133815e-16, -2.22044605e-16,
         4.44089210e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-4.44089210e-16, -1.11022302e-15,  1.00000000e+00,
         4.44089210e-16],
       [-8.88178420e-16, -4.44089210e-16,  1.11022302e-16,
         1.00000000e+00]])

In [125]:
# Operations over an axis
print(np.sum(X, axis=0)) # Vertical
np.sum(X, axis=1) # Horizontal

[16 25 25  9]


array([18,  5, 29, 23])

In [41]:
# Example: Evaluating Training Accuracy
y_train = [0, 1, 1, 0]
y_true =  [1, 1, 1, 0]

accuracy = np.sum(np.array(y_train) == np.array(y_true)) / len(y_train)
print(f'Train accuracy: {accuracy * 100:.4}%')

Train accuracy: 75.0%


## NumPy Sampling

In [42]:
# Flip a coin
np.random.seed(1518)
np.random.binomial(n=1, p=0.5)

1

In [43]:
# Flip 10 coins IID
np.random.binomial(n=1, p=0.5, size=10)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [44]:
# Flip 10 coins and count number of heads
np.random.binomial(n=10, p=0.5)

5

In [45]:
# Shuffling
data = np.array([1, 2, 3, 4, 5, 6])
np.random.shuffle(data)
data

array([6, 3, 1, 5, 2, 4])

In [46]:
# Better solution
data = np.array([1, 2, 3, 4, 5, 6])
np.random.choice(data)

4

In [47]:
# Multivariate normal
means = [0, 0]
sigma = np.identity(2)
np.random.multivariate_normal(means, sigma)

array([-0.70142666, -0.52730675])

Summary:
- numpy arrays are very fast for operations we want to use compared to lists
- numpy arrays sizes/dimensions are fixed in place
- The numpy library contains a wide variety of tools to help us, sometimes overlapping with other
- Numpy arrays only support one datatype

# Part 3: How to Define a Python Class

Why we need Class: easier to manage different instances with different attributes.

In [45]:
class Dog:
    def __init__(self, name, age, gender, breed):
        self.name = name  # Attribute
        self.age = age
        self.gender = gender
        self.breed = breed

    # Method
    def bark(self, repeat_times=3):
        print("Woof! " * repeat_times)

    # Method
    def introduce(self):
        print(f"my name is {self.name}, I am a {self.age} years old {self.gender} {self.breed} dog.")

In [46]:
# Instance == a special case / instantiation / example of class
bc_dog = Dog(name='coco', age=1, gender='female', breed='border collie')

In [47]:
bc_dog

In [49]:
bc_dog.bark(repeat_times=10)

Woof! Woof! Woof! Woof! Woof! Woof! Woof! Woof! Woof! Woof! 


In [50]:
bc_dog.introduce()

my name is coco, I am a 1 years old female border collie dog.


In [51]:
# Instance == a special case / instantiation / example of class
la_dog = Dog(name='marko', age=5, gender='male', breed='labrador')

In [52]:
la_dog.bark()

Woof! Woof! Woof! 


In [53]:
la_dog.introduce()

my name is marko, I am a 5 years old male labrador dog.


# Part 4: Python Class of Single Layer Perceptron Classifier for XOR, AND Examples

XOR examples cannot be solved by Single Layer Perceptron, while AND examples can.

The following code matches slide page 6/29 CH1_Sec3 Perceptron Machine and Universal Approximation.pdf.

In [56]:
import numpy as np

# Machine Learning Model class
class SingleLayerPerceptron:
    def __init__(self, input_size, epochs=10000):
        # Initialize weights and bias
        self.weights = np.random.uniform(-1, 1, input_size)
        self.bias = np.random.uniform(-1, 1)
        self.epochs = epochs


    # Method: Forward pass
    def forward(self, x):
        linear_output = np.dot(x, self.weights) + self.bias   # y = Xw + b
        return linear_output

    # Indicator loss function (0-1 loss)
    def indicator_loss(self, y_true, y_pred):
        return np.sum(y_pred != y_true)  # Count mismatches (1 if incorrect, 0 if correct)

    # Training the perceptron using gradient descent
    def train(self, X, y):
        for epoch in range(self.epochs):
            total_loss = 0  # Track total loss for this epoch
            
            for i in range(len(X)):
                # Forward pass
                z = self.forward(X[i])
                y_pred = np.where(z >= 0, 1, 0)

                # Calculate the indicator loss for current prediction
                loss = self.indicator_loss(y[i], y_pred)

                # If there's a mismatch, perform weight update (Gradient Descent)
                if loss > 0:
                    self.weights -= np.sign(z) * X[i]
                    self.bias -= np.sign(z)
                
                total_loss += loss

            # Print the total loss every 1000 epochs for monitoring
            if epoch % 1000 == 0:
                print(f'Epoch {epoch}, Total Loss: {total_loss} Weights: {self.weights, self.bias}')

    # Prediction method
    def predict(self, X):
        output = self.forward(X)
        return np.where(output >= 0, 1, 0)



# XOR dataset: can't be solved by single layer perceptron
# X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# y = np.array([0, 1, 1, 0])

# AND dataset: can be solved by single layer perceptron
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

# OR dataset: can be solved by single layer perceptron
# X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# y = np.array([0, 1, 1, 1])

# Initialize the perceptron with 2-dimensional inputs
perceptron = SingleLayerPerceptron(input_size=2)

# Train the perceptron
perceptron.train(X, y)

# Predictions
predictions = perceptron.predict(X)
print("Predicted label", predictions)
print("True label", y)

print(f"Accuracy: {100*np.sum(predictions == y) / len(y)}%")
# plt.plot(perceptron.loss_history)
# plt.xlabel('Epoch')
# plt.ylabel('Loss')

Epoch 0, Total Loss: 3 Weights: (array([0.83578739, 0.98571061]), -0.22018116833206536)
Epoch 1000, Total Loss: 0 Weights: (array([1.83578739, 0.98571061]), -2.2201811683320654)
Epoch 2000, Total Loss: 0 Weights: (array([1.83578739, 0.98571061]), -2.2201811683320654)
Epoch 3000, Total Loss: 0 Weights: (array([1.83578739, 0.98571061]), -2.2201811683320654)
Epoch 4000, Total Loss: 0 Weights: (array([1.83578739, 0.98571061]), -2.2201811683320654)
Epoch 5000, Total Loss: 0 Weights: (array([1.83578739, 0.98571061]), -2.2201811683320654)
Epoch 6000, Total Loss: 0 Weights: (array([1.83578739, 0.98571061]), -2.2201811683320654)
Epoch 7000, Total Loss: 0 Weights: (array([1.83578739, 0.98571061]), -2.2201811683320654)
Epoch 8000, Total Loss: 0 Weights: (array([1.83578739, 0.98571061]), -2.2201811683320654)
Epoch 9000, Total Loss: 0 Weights: (array([1.83578739, 0.98571061]), -2.2201811683320654)
Predicted label [0 0 0 1]
True label [0 0 0 1]
Accuracy: 100.0%


# Part 5: Q&A